server:
  port: 8080

server-url: 'http://localhost:8080'
server-route:



spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/moodle
    username: postgres
    password: postgres
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    baselineOnMigrate: true
    locations: 'classpath:db.migration'
    schemas: 'public'
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    enabled: false
jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

