alter table if exists question drop constraint if exists test_fk;
alter table if exists question_result drop constraint if exists question_fk;
alter table if exists question_result drop constraint if exists user_fk;

drop table if exists question cascade;
drop table if exists question_result cascade;

create table question
(
    id          int8 generated by default as identity,
    test_id     int8         not null,
    user_id     int8         not null,
    "name"      varchar(255) not null,
    description varchar(255) not null,
    solution    varchar(255) not null,
    primary key (id, test_id)
);

create table question_result
(
    question_id int8         not null,
    user_id     int8         not null,
    test_id     int8         not null,
    answer      varchar(255) not null,
    "right"     varchar(255) not null,
    primary key (question_id, user_id)
);

alter table if exists question_result add constraint user_fk foreign key (user_id) references users;
alter table if exists question_result add constraint question_res_fk foreign key (question_id, test_id) references question;
alter table if exists question add constraint question_fk foreign key (test_id, user_id) references test;